### ISSUE TITLE
Remove /out from git and use a build action to do it instead

### ISSUE THREAD

**Issue by sophiemachin** [THIS-Institute/qualtrics-thiscovery-skin#35]
It's tedious having to commit builds of the docs

Instead, just commit the source code and have github create the built pages

**Comment by glinkan** [comment]
But the docstrings are in the source code, which you'd have to commit anyway? Not seeing the tedious bit here?

**Comment by sophiemachin** [comment]
Every time you run the `build` command the files in /out get updated, and are under git. Even files that you didn't touch.
